### ISSUE TITLE
LESS Compiler Version

### ISSUE THREAD

**Issue by utroda** [carlcalderon/Rocket#7]
How do you find what version of the less compiler is being used and how to change or update it?

Thanks

**Comment by carlcalderon** [comment]
Rocket comes packed with LESS 1.3.0 but if you need a later version you may either use the Custom Compilers (https://github.com/carlcalderon/Rocket#custom-compilers) or update LESS manually by simply going here "/usr/local/lib/rocket/" and do "$ sudo npm update less". The later may cause compile issues if LESS has changed input scheme past 1.3.0.

**Comment by utroda** [comment]
Its kinda, weird because the less site (lesscss.org) says they are on version 1.3.3, but their repo is on version 1.4.0 ( https://github.com/cloudhead/less.js )

As you can see in 1.4.0 they have a bunch more helpful functions ( http://lesscss.org/#reference )

Do you think upgrading to 1.4.0 would break rocket?

**Comment by carlcalderon** [comment]
I don't think updating less will cause any major issues. I will however update all compilers very soon and I could start by updating just less. Next thing for Rocket is going to be better integration with the compilers using the ones currently on the system rather than ones packed with Rocket. I will try to update less and the other compilers this weekend.

**Comment by utroda** [comment]
Sounds good, will hold tight and wait for an update, thanks for the help.

**Comment by carlcalderon** [comment]
You are quite welcome!

**Comment by carlcalderon** [comment]
All compilers are now updated (see [Change Log](https://github.com/carlcalderon/Rocket#023002)) pushed version up to 0.2.3+0.0.2 (former 0.0.1 build).
