### ISSUE TITLE
Compiling Ember.js Fails

### ISSUE THREAD

**Issue by utroda** [carlcalderon/Rocket#8]
Using the latest build from the EmberJS site ( http://builds.emberjs.com/ember-1.0.0-rc.5.js ) rocket build will fail.

My config looks like 

```
        {
                    "input": [
                        "assets/js/libs/jquery/jquery-1.9.1.js",
                        "assets/js/libs/handlebars/handlebars.js",
                        "assets/js/libs/ember/ember.js",
                        "assets/js/app.js"
                    ],
                    "output": "assets/js/scripts.js",
                    "compiler" : "uglify",
                    "minify": true
                }
```

If i comment out ember it will compile just fine, and rocket just outputs the ember.js file so i can't see the actually error that its returning. 

Any ideas?

**Comment by carlcalderon** [comment]
Should be fixed with the latest deploy. You can get the latest version using "$ rocket --update". Ember was actually too big as an output so Rocket hit the maximum buffer size and hence not outputting the actual error since the buffer was already full.

Also; you don't have to specify `uglify` as a compiler when you have `minify` set to `true` when the input is js. `minify: true` will use uglify anyway. Your current config setup will minify twice. See [Packed Compilers](https://github.com/carlcalderon/Rocket#packaged-compilers) "invoke by" column for more info.

Cheers and thank you for spotting this!
